[package]
name = "many_body_simulation"
version = "0.1.0"
edition = "2024"

[profile.dev]
debug = 2
opt-level = 0 # Switch to 1 for more runtime performance
overflow-checks = false # Uncomment for better math performance

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = 0
opt-level = 3
panic = "abort"
strip = "debuginfo"

[profile.distribution]
inherits = "release"
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[profile.wasm]
inherits = "release"
codegen-units = 1
debug = 0
lto = true
opt-level = "z"
strip = true

[dependencies]
bevy_panorbit_camera = "*"
rand = "0.9.*"
rand_chacha = "0.9.*"
libm = "0.2.15"

[dev-dependencies]
statrs = "*"

# Native-specific avian3d with parallel processing
[dependencies.avian3d]
version = "*"
default-features = false
features = [
    "3d",
    "bevy_diagnostic",
    "collider-from-mesh",
    "debug-plugin",
    "diagnostic_ui",
    "enhanced-determinism",
    "f64",
    "parallel",
    "parry-f64",
]

[dependencies.bevy]
version = "0.16.*"
features = ["libm", "default_no_std"]

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.*"
web-sys = "0.*"
getrandom = { version = "0.*", features = ["wasm_js"] }

[features]
dev = [
    "bevy/asset_processor",
    "bevy/embedded_watcher",
    "bevy/default_font",
    "bevy/dynamic_linking",
    "bevy/file_watcher",
]
