[package]
name = "many_body_simulation"
version = "0.1.0"
edition = "2024"

[profile.dev]
debug = 2
opt-level = 0 # Switch to 1 for more runtime performance
overflow-checks = false # Uncomment for better math performance

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = 0
opt-level = 3
panic = "abort"
strip = "debuginfo"

[profile.distribution]
inherits = "release"
codegen-units = 1
lto = true
strip = true

[dependencies]
bevy = "0.16.*"
bevy_panorbit_camera = "*"
rand = "0.9.*"
rand_chacha = "0.9.*"

[dev-dependencies]
statrs = "*"

# Native-specific avian3d with parallel processing
[target.'cfg(not(target_arch = "wasm32"))'.dependencies.avian3d]
version = "*"
features = [
    "3d",
    "bevy_diagnostic",
    "collider-from-mesh",
    "debug-plugin",
    "diagnostic_ui",
    "enhanced-determinism",
    "parallel",
]

# WASM-specific avian3d
[target.'cfg(target_arch = "wasm32")'.dependencies.avian3d]
version = "*"
features = [
    "3d",
    "bevy_diagnostic",
    "collider-from-mesh",
    "default-collider",
    "diagnostic_ui",
    "enhanced-determinism",
    "f32",
]

# Native-specific features
[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bevy]
version = "0.16.*"
default-features = false
features = [
    "multi_threaded",
]

# WASM-specific features
[target.'cfg(target_arch = "wasm32")'.dependencies.bevy]
version = "0.16.*"
default-features = false
features = [
    "webgl2",
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.*"
web-sys = "0.*"
getrandom = { version = "0.*", features = ["wasm_js"] }

[features]
dev = [
    "bevy/asset_processor",
    "bevy/embedded_watcher",
    "bevy/default_font",
    "bevy/dynamic_linking",
    "bevy/file_watcher",
]
default = []
diagnostics_hud = [
    "avian3d/bevy_diagnostic",
    "avian3d/diagnostic_ui",
]
