[package]
name = "stardrift"
version = "0.0.1"
edition = "2024"
license = "CC0-1.0"

[package.metadata.bundle]
name = "Stardrift"
category = "Game"

[profile.dev]
debug = 2
opt-level = 0

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = 0
opt-level = 3
panic = "abort"
strip = "debuginfo"

[profile.distribution]
inherits = "release"
codegen-units = 1
lto = true
strip = true

[profile.bench]
inherits = "distribution"

[profile.wasm]
inherits = "distribution"

[dependencies]
bevy_panorbit_camera = "*"
config = "0.15"
directories = "6"
libm = "0.2"
rand = "0.9"
rand_chacha = "0.9"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[dependencies.bevy]
version = "0.16.*"
default-features = false
features = [
    "default_no_std",
    "libm",
    "zstd",
    "reflect_functions",
    "reflect_documentation",
    "bevy_ui",
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_log",
    "bevy_pbr",
    "bevy_render",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_window",
    "bevy_winit",
    "hdr",
    "multi_threaded",
    "sysinfo_plugin",
    "tonemapping_luts",
    "webgl2",
    "x11",
]

[dependencies.avian3d]
version = "*"
default-features = false
features = ["3d", "enhanced-determinism", "f64", "parallel", "parry-f64"]

[dev-dependencies]
criterion = { version = "0.6", features = ["csv_output", "html_reports"] }

[[bin]]
name = "stardrift"
path = "src/main.rs"

[features]
default = ["graphics"]
graphics = []
diagnostics = []
benchmarks = []

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.*"
web-sys = "0.*"
getrandom = { version = "0.*", features = ["wasm_js"] }

[[bench]]
name = "octree_benchmarks"
harness = false
